# Sử dụng Docker image PHP chính thức
image: php:8.1

# Định nghĩa các stages của pipeline
stages:
  - build
  - test
  - deploy

# Job để cài đặt các phụ thuộc và xây dựng ứng dụng
build:
  stage: build
  script:
    - composer install

# Job để chạy các bài kiểm tra (nếu có)
test:
  stage: test
  script:
    - php vendor/bin/phpunit --configuration phpunit.xml

# Job để triển khai ứng dụng (đơn giản hóa ví dụ, tuỳ chỉnh theo nhu cầu)
deploy:
  stage: deploy
  script:
    - echo "Deploying to production server..."
    - scp -r . user@your-server:/path/to/deploy
  only:
    - master
